name: CI (Win10兼容x64)

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: [
      '.github/workflows/release.yml',
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp',
      '**/*.cu',
      '**/*.cuh',
      '**/*.swift',
      '**/*.m',
      '**/*.metal',
      '**/*.comp',
      '**/*.glsl'
    ]

  pull_request:
    types: [opened, reopened]
    paths: [
      '**/CMakeLists.txt',
      '**/.cmake',
      '**/*.h',
      '**/*.hpp',
      '**/*.c',
      '**/*.cpp'
    ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREAD: 1
  LLAMA_LOG_COLORS: 1
  LLAMA_LOG_PREFIX: 1
  LLAMA_LOG_TIMESTAMPS: 1

jobs:
  windows-latest:
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - build: 'cpu-x64 (static)'
            arch: 'x64'
            defines: '-G "Ninja Multi-Config" -D CMAKE_TOOLCHAIN_FILE=cmake/x64-windows-llvm.cmake -DGGML_NATIVE=OFF -DLLAMA_BUILD_SERVER=ON -DGGML_RPC=ON -DBUILD_SHARED_LIBS=OFF -DGGML_OPENMP=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_TOOLS=ON -DLLAMA_FATAL_WARNINGS=ON'
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "tools/ui/package-lock.json"

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: windows-latest-${{ matrix.build }}
          variant: ccache
          evict-old-files: 1d

      - name: Install Ninja
        run: choco install ninja

      - name: Build
        run: |
          cmake -S . -B build ${{ matrix.defines }} `
            -DLLAMA_BUILD_BORINGSSL=ON
          cmake --build build --config Release -j ${env:NUMBER_OF_PROCESSORS}

      - name: Build Web UI
        run: |
          cd tools/ui
          npm ci
          npm run build

      - name: ccache-clear
        uses: ./.github/actions/ccache-clear
        with:
          key: windows-latest-${{ matrix.build }}

      - name: Test
        if: ${{ matrix.arch == 'x64' }}
        run: |
          cd build
          ctest -L main -C Release --verbose --timeout 900

      - name: Pack
        run: |
          if (Test-Path tools/ui/dist) {
            Copy-Item -Recurse tools/ui/dist build/bin/Release/ui
          }
          7z a -snl llama-bin-win-cpu-x64-static-win10.zip ./build/bin/Release/*

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: llama-bin-win-cpu-x64-static-win10
          path: llama-bin-win-cpu-x64-static-win10.zip

  # ==========================
  # 自动发布（带 TAG）
  # ==========================
  release:
    needs: windows-latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Generate tag
        id: tag
        run: echo "tag=build-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Windows 10 纯CPU静态版
          tag_name: ${{ steps.tag.outputs.tag }}
          files: artifacts/llama-bin-win-cpu-x64-static-win10.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
